apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    platform.sremayank.io/owner: payments
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api
  namespace: payments
  annotations:
    iam.gke.io/gcp-service-account: payments-api@example-project.iam.gserviceaccount.com
